src/Domain/Authentication/Entity/User.php
<?php

declare(strict_types=1);

namespace Domain\Authentication\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Domain\Authentication\ValueObject\Gender;
use Domain\Authentication\ValueObject\Roles;
use Domain\Report\Entity\Evaluation;
use Domain\Report\Entity\Report;
use Domain\Shared\Entity\{IdentityTrait, TimestampTrait};
use Scheb\TwoFactorBundle\Model\BackupCodeInterface;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface as EmailTwoFactor;
use Scheb\TwoFactorBundle\Model\Google\TwoFactorInterface as GoogleTwoFactor;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @TODO find a way to remove symfony interfaces from the domain model user
 * Class User
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface, GoogleTwoFactor, EmailTwoFactor, BackupCodeInterface, \Stringable
{
    use IdentityTrait;
    use TimestampTrait;
    use BackupAuthTrait;
    use TwoFactorAuthTrait;

    private ?string $username = null;

    private ?string $job_title = null;

    private Gender $gender;

    private ?string $email = null;

    private Roles $roles;

    private ?string $password = null;

    private ?\DateTimeImmutable $last_login_at = null;

    private ?string $last_login_ip = null;

    private ?\DateTimeImmutable $notifications_read_at = null;

    /**
     * @var Collection<Report>
     */
    private Collection $submitted_reports;

    /**
     * @var Collection<Report>
     */
    private Collection $assigned_reports;

    /**
     * @var Collection<Evaluation>
     */
    private Collection $evaluations;

    public function __construct()
    {
        $this->gender = Gender::male();
        $this->roles = Roles::employee();
        $this->evaluations = new ArrayCollection();
        $this->submitted_reports = new ArrayCollection();
        $this->assigned_reports = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->username;
    }

    public static function create(
        string $username,
        string $email,
        string $password,
        bool $is_admin = false
    ): self {
        return (new self())
            ->setUsername($username)
            ->setEmail($email)
            ->setPassword($password)
            ->setRoles($is_admin ? Roles::admin() : Roles::employee());
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->job_title;
    }

    public function setJobTitle(?string $job_title): self
    {
        $this->job_title = $job_title;

        return $this;
    }

    public function getGender(): Gender
    {
        return $this->gender;
    }

    public function setGender(Gender|string $gender): self
    {
        if ($gender instanceof Gender) {
            $this->gender = $gender;
        } else {
            $this->gender = Gender::fromString($gender);
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles->toArray();
    }

    public function setRoles(Roles|array $roles): self
    {
        if ($roles instanceof Roles) {
            $this->roles = $roles;
        } else {
            $this->roles = Roles::fromArray($roles);
        }

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getLastLoginAt(): ?\DateTimeImmutable
    {
        return $this->last_login_at;
    }

    public function setLastLoginAt(?\DateTimeInterface $last_login_at): self
    {
        if (null !== $last_login_at) {
            $this->last_login_at = \DateTimeImmutable::createFromInterface($last_login_at);
        } else {
            $this->last_login_at = null;
        }

        return $this;
    }

    public function getLastLoginIp(): ?string
    {
        return $this->last_login_ip;
    }

    public function setLastLoginIp(?string $last_login_ip): self
    {
        $this->last_login_ip = $last_login_ip;

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials(): void
    {
    }

    /**
     * @inheritDoc
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->getEmail();
    }

    public function hasRole(string $role): bool
    {
        if ('ROLE_USER' === $role && 1 !== count($this->getRoles())) {
            return false;
        }

        return in_array($role, $this->getRoles(), true);
    }

    public function getSubmittedReports(): Collection
    {
        return $this->submitted_reports;
    }

    public function setSubmittedReports(Collection $reports): self
    {
        $this->submitted_reports = $reports;

        return $this;
    }

    public function getAssignedReports(): Collection
    {
        return $this->assigned_reports;
    }

    public function addAssignedReport(Report $report): self
    {
        if (! $this->assigned_reports->contains($report)) {
            $this->assigned_reports[] = $report;
            $report->addManager($this);
        }

        return $this;
    }

    public function removeAssignedReport(Report $report): self
    {
        if ($this->assigned_reports->removeElement($report)) {
            $report->removeManager($this);
        }

        return $this;
    }

    public function getEvaluations(): Collection
    {
        return $this->evaluations;
    }

    public function setEvaluations(Collection $evaluations): self
    {
        $this->evaluations = $evaluations;

        return $this;
    }

    public function getAutocompleteValue(): string
    {
        return (string) $this->id;
    }

    public function getAutocompleteLabel(): string
    {
        return (string) $this->username;
    }

    public function getNotificationsReadAt(): ?\DateTimeImmutable
    {
        return $this->notifications_read_at;
    }

    public function setNotificationsReadAt(?\DateTimeImmutable $notifications_read_at): self
    {
        $this->notifications_read_at = $notifications_read_at;

        return $this;
    }
}

src/Domain/Shared/Entity/IdentityTrait.php
<?php

declare(strict_types=1);

namespace Domain\Shared\Entity;

/**
 * Trait IdentityTrait.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
trait IdentityTrait
{
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }
}

src/Infrastructure/Shared/Symfony/Form/AbstractForm.php
<?php

declare(strict_types=1);

namespace Infrastructure\Shared\Symfony\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Construit un formulaire automatiquement en se basant sur les propriétés
 * d'un objet (un DTO dans le cas de figure).
 *
 * Class AbstractForm
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
abstract class AbstractForm extends AbstractType
{
    protected const TYPES = [
        'string' => TextType::class,
        'bool' => CheckboxType::class,
        'int' => NumberType::class,
        'float' => NumberType::class,
        \DateTimeInterface::class => DateTimeType::class,
        UploadedFile::class => FileType::class,
    ];

    protected const NAMES = [
        'color' => ColorType::class,
    ];

    /**
     * @throws \ReflectionException
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        /** @var object $data */
        $data = $options['data'];
        $reflection = new \ReflectionClass($data);
        $properties = $reflection->getProperties(\ReflectionProperty::IS_PUBLIC);

        foreach ($properties as $property) {
            $name = $property->getName();

            /** @var \ReflectionNamedType|\ReflectionUnionType|null $type */
            $type = $property->getType();

            if (null === $type || $type instanceof \ReflectionUnionType) {
                break;
            }

            if (array_key_exists($name, self::NAMES)) {
                $builder->add($name, self::NAMES[$name], [
                    'required' => false,
                ]);
            } elseif (array_key_exists($type->getName(), self::TYPES)) {
                $builder->add($name, self::TYPES[$type->getName()], [
                    'required' => ! $type->allowsNull() && 'bool' !== $type->getName(),
                ]);
            } else {
                throw new \RuntimeException(sprintf('Could not find the field associated with the type %s in %s::%s', $type->getName(), $data::class, $name));
            }
        }
    }
}

src/Infrastructure/Shared/Symfony/Form/Type/AutoGrowTextareaType.php
<?php

declare(strict_types=1);

namespace Infrastructure\Shared\Symfony\Form\Type;

use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class AutoGrowTextareaType.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
class AutoGrowTextareaType extends TextareaType
{
    public function configureOptions(OptionsResolver $resolver): OptionsResolver
    {
        parent::configureOptions($resolver);
        $resolver->setDefaults([
            'attr' => [
                'is' => 'app-textarea-autogrow',
                'row' => 20,
            ],
        ]);

        return $resolver;
    }
}

src/Infrastructure/Shared/Symfony/Form/Type/DatePickerType.php
<?php

declare(strict_types=1);

namespace Infrastructure\Shared\Symfony\Form\Type;

use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class DatePickerType.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
class DatePickerType extends DateTimeType
{
    public function configureOptions(OptionsResolver $resolver): OptionsResolver
    {
        parent::configureOptions($resolver);
        $resolver->setDefaults([
            'attr' => [
                'is' => 'app-datepicker',
            ],
            'input_format' => 'Y-m-d H:i',
            'html5' => false,
            'widget' => 'single_text',
        ]);

        return $resolver;
    }
}

src/Infrastructure/Shared/Symfony/Controller/AbstractController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Shared\Symfony\Controller;

use Domain\Shared\Exception\SafeMessageException;
use Infrastructure\Shared\Symfony\Messenger\DispatchTrait;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController as SymfonyAbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Class AbstractController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
abstract class AbstractController extends SymfonyAbstractController
{
    use DispatchTrait;

    public function __construct(
        protected readonly MessageBusInterface $commandBus,
        protected readonly TranslatorInterface $translator,
        protected readonly LoggerInterface $logger
    ) {
    }

    protected function redirectSeeOther(string $route, array $params = []): RedirectResponse
    {
        return $this->redirectToRoute($route, $params, Response::HTTP_SEE_OTHER);
    }

    protected function getResponseBasedOnFormValidationStatus(FormInterface $form, ?Response $response = null): Response
    {
        if (null === $response) {
            $response = new Response();
        }

        if (Response::HTTP_OK === $response->getStatusCode() && $form->isSubmitted() && ! $form->isValid()) {
            $response->setStatusCode(Response::HTTP_UNPROCESSABLE_ENTITY);
        }

        return $response;
    }

    protected function flashFormErrors(FormInterface $form): void
    {
        $errors = $this->getFormErrors($form);
        $errors = iterator_to_array(new \RecursiveIteratorIterator(new \RecursiveArrayIterator($errors)));
        $this->addFlash(
            type: 'error',
            message: implode(separator: '\n', array: $errors)
        );
    }

    protected function getFormErrors(FormInterface $form): array
    {
        $errors = [];
        foreach ($form->getErrors() as $error) {
            $errors[] = $error->getMessage();
        }

        foreach ($form->all() as $childForm) {
            if ($childForm instanceof FormInterface) {
                $childErrors = $this->getFormErrors($childForm);
                if ($childErrors) {
                    $errors[] = $childErrors;
                }
            }
        }

        return $errors;
    }

    protected function handleUnexpectedException(\Throwable $e): void
    {
        if ($e instanceof SafeMessageException) {
            $message = $this->getSafeMessageException($e);
        } else {
            $message = $this->translator->trans(
                id: 'flashes.something_went_wrong',
                parameters: [],
                domain: 'messages'
            );
        }

        $this->logger->error($e->getMessage(), $e->getTrace());
        $this->addFlash('error', $message);
    }

    protected function getSafeMessageException(SafeMessageException $e): string
    {
        return $this->translator->trans(
            id: $e->getMessageKey(),
            parameters: $e->getMessageData(),
            domain: $e->getMessageDomain()
        );
    }

    protected function addSomethingWentWrongFlash(): void
    {
        $this->addFlash('error', $this->translator->trans(
            id: 'flashes.something_went_wrong',
            parameters: [],
            domain: 'messages'
        ));
    }
}

src/Infrastructure/Shared/Symfony/Controller/DeleteCsrfTrait.php
<?php

declare(strict_types=1);

namespace Infrastructure\Shared\Symfony\Controller;

use Symfony\Component\HttpFoundation\Request;

/**
 * Trait DeleteCsrfTrait.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
trait DeleteCsrfTrait
{
    public function isDeleteCsrfTokenValid(string $id, Request $request): bool
    {
        return $this->isCsrfTokenValid(
            "delete_{$id}",
            (string) $request->request->get('_token')
        );
    }
}

src/Infrastructure/Shared/Symfony/Controller/HomeController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Shared\Symfony\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class HomeController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[IsGranted('IS_AUTHENTICATED')]
final class HomeController extends AbstractController
{
    #[Route('/', name: 'app_index', methods: ['GET'])]
    public function index(): Response
    {
        return $this->render('domain/home.html.twig');
    }
}

src/Infrastructure/Shared/Symfony/Controller/OfflineController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Shared\Symfony\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class OfflineController extends AbstractController
{
    #[Route('/offline')]
    public function offline(): Response
    {
        return $this->render('shared/offline.html.twig');
    }
}

src/Infrastructure/Shared/Symfony/Controller/PaginationAssertionTrait.php
<?php

declare(strict_types=1);

namespace Infrastructure\Shared\Symfony\Controller;

use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Trait PaginationAssertionTrait.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
trait PaginationAssertionTrait
{
    protected function assertIsGreaterThanZero(mixed $page): void
    {
        if (! is_int($page) || $page <= 0) {
            throw new BadRequestHttpException();
        }
    }

    protected function assertNonEmptyData(int $page, \Countable $data): void
    {
        if ($page > 1 && 0 === $data->count()) {
            throw new NotFoundHttpException();
        }
    }
}

templates/shared/layout/base.html.twig
{% apply spaceless %}
    <!DOCTYPE html>
    <html lang="{{ app.request.locale() | default('fr') }}">
    <head>
        <meta charset="utf-8">
        <meta name="author" content="devscast">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" href="{{ asset('/images/logo_icon.png') }}">
        <title>{% block title %}{% endblock %} | UNH Rapports</title>

        {# PWA support #}
        <meta name="theme-color" content="#6576ff">
        <link rel="manifest" href="{{ asset('manifest.json') }}">

        {# PWA Support IOS #}
        <link rel="apple-touch-icon" sizes="128x128" href="{{ asset('images/icons/maskable_icon_x128.png') }}">
        <link rel="apple-touch-icon" sizes="192x192" href="{{ asset('images/icons/maskable_icon_x192.png') }}">
        <link rel="apple-touch-startup-image" href="{{ asset('images/icons/maskable_icon.png') }}">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">

        {% block meta %}{% endblock %}
        {{ encore_entry_link_tags('app') }}
        {% block stylesheets %}{% endblock %}

        <script defer data-turbo-track="reload" src="{{ asset('/static/bundle.js') }}"></script>

        {{ encore_entry_script_tags('app') }}
    </head>
    <body class="nk-body bg-lighter has-sidebar ui-shady" {{ stimulus_controller('turbo') }}>
    {% include 'shared/component/_flash.html.twig' %}
    <div class="nk-app-root">
        <div class="nk-main">
            {% block sidebar %}
                {% embed "shared/component/_sidebar.html.twig" %}{% endembed %}
            {% endblock %}
            <div class="nk-wrap">
                {% block navbar %}
                    {% include 'shared/component/_navbar.html.twig' %}
                {% endblock %}
                <div class="nk-content">
                    <div class="container-fluid">
                        <div class="nk-content-inner">
                            {% block body %}
                                <div class="nk-content-body">
                                    {% block header %}{% endblock %}
                                    <div class="nk-block">
                                        {% block content %}{% endblock %}
                                    </div>
                                </div>
                            {% endblock %}
                        </div>
                    </div>
                </div>
                {% block footer %}
                    {% embed "shared/component/_footer.html.twig" %}{% endembed %}
                {% endblock %}
            </div>
        </div>
    </div>

    <script>
        window.unh_report = {
            ...(window.unh_report || {}),
            ADMIN: {{ is_granted('ROLE_ADMIN') ? 'true' : 'false' }},
            USER: {{ app.user ? app.user.id : 'null' }},
            MERCURE_URL: "{{ mercure_subscribe_url }}",
            BASE_URL: "{{ app.request.schemeAndHttpHost }}",
            NOTIFICATION: new Date({{ (app.user and app.user.notificationsReadAt) ? app.user.notificationsReadAt.timestamp * 1000 : 0 }})
        }
    </script>
    {% block javascripts %}{% endblock %}
    </body>
    </html>
{% endapply %}

templates/shared/layout/error.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}" class="js">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ asset('images/logo_icon.png') }}">
    <title>{{ exception.statusCode }} {{ exception.statusText }} | UNH Rapports</title>
    {{ encore_entry_link_tags('app') }}
    {{ encore_entry_script_tags('app')}}
</head>

<body class="nk-body bg-white npc-default pg-error">
<div class="nk-app-root">
    <div class="nk-main ">
        <div class="nk-wrap nk-wrap-nosidebar">
            <div class="nk-content ">
                <div class="nk-block nk-block-middle wide-xs mx-auto">
                    <div class="nk-block-content nk-error-ld text-center">
                        <h1 class="nk-error-head">{{ exception.statusCode }}</h1>
                        <h3 class="nk-error-title">{{ exception.statusText }}</h3>
                        <p class="nk-error-text">Désolé nous n'arrivons pas à charger cette page...</p>
                        <a href="{{ path('app_index') }}" class="btn btn-lg btn-primary mt-2">Rentrer sur terre</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>