src/Domain/Authentication/Entity/User.php
<?php

declare(strict_types=1);

namespace Domain\Authentication\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Domain\Authentication\ValueObject\Gender;
use Domain\Authentication\ValueObject\Roles;
use Domain\Report\Entity\Evaluation;
use Domain\Report\Entity\Report;
use Domain\Shared\Entity\{IdentityTrait, TimestampTrait};
use Scheb\TwoFactorBundle\Model\BackupCodeInterface;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface as EmailTwoFactor;
use Scheb\TwoFactorBundle\Model\Google\TwoFactorInterface as GoogleTwoFactor;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @TODO find a way to remove symfony interfaces from the domain model user
 * Class User
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface, GoogleTwoFactor, EmailTwoFactor, BackupCodeInterface, \Stringable
{
    use IdentityTrait;
    use TimestampTrait;
    use BackupAuthTrait;
    use TwoFactorAuthTrait;

    private ?string $username = null;

    private ?string $job_title = null;

    private Gender $gender;

    private ?string $email = null;

    private Roles $roles;

    private ?string $password = null;

    private ?\DateTimeImmutable $last_login_at = null;

    private ?string $last_login_ip = null;

    private ?\DateTimeImmutable $notifications_read_at = null;

    /**
     * @var Collection<Report>
     */
    private Collection $submitted_reports;

    /**
     * @var Collection<Report>
     */
    private Collection $assigned_reports;

    /**
     * @var Collection<Evaluation>
     */
    private Collection $evaluations;

    public function __construct()
    {
        $this->gender = Gender::male();
        $this->roles = Roles::employee();
        $this->evaluations = new ArrayCollection();
        $this->submitted_reports = new ArrayCollection();
        $this->assigned_reports = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->username;
    }

    public static function create(
        string $username,
        string $email,
        string $password,
        bool $is_admin = false
    ): self {
        return (new self())
            ->setUsername($username)
            ->setEmail($email)
            ->setPassword($password)
            ->setRoles($is_admin ? Roles::admin() : Roles::employee());
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->job_title;
    }

    public function setJobTitle(?string $job_title): self
    {
        $this->job_title = $job_title;

        return $this;
    }

    public function getGender(): Gender
    {
        return $this->gender;
    }

    public function setGender(Gender|string $gender): self
    {
        if ($gender instanceof Gender) {
            $this->gender = $gender;
        } else {
            $this->gender = Gender::fromString($gender);
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles->toArray();
    }

    public function setRoles(Roles|array $roles): self
    {
        if ($roles instanceof Roles) {
            $this->roles = $roles;
        } else {
            $this->roles = Roles::fromArray($roles);
        }

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getLastLoginAt(): ?\DateTimeImmutable
    {
        return $this->last_login_at;
    }

    public function setLastLoginAt(?\DateTimeInterface $last_login_at): self
    {
        if (null !== $last_login_at) {
            $this->last_login_at = \DateTimeImmutable::createFromInterface($last_login_at);
        } else {
            $this->last_login_at = null;
        }

        return $this;
    }

    public function getLastLoginIp(): ?string
    {
        return $this->last_login_ip;
    }

    public function setLastLoginIp(?string $last_login_ip): self
    {
        $this->last_login_ip = $last_login_ip;

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials(): void
    {
    }

    /**
     * @inheritDoc
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->getEmail();
    }

    public function hasRole(string $role): bool
    {
        if ('ROLE_USER' === $role && 1 !== count($this->getRoles())) {
            return false;
        }

        return in_array($role, $this->getRoles(), true);
    }

    public function getSubmittedReports(): Collection
    {
        return $this->submitted_reports;
    }

    public function setSubmittedReports(Collection $reports): self
    {
        $this->submitted_reports = $reports;

        return $this;
    }

    public function getAssignedReports(): Collection
    {
        return $this->assigned_reports;
    }

    public function addAssignedReport(Report $report): self
    {
        if (! $this->assigned_reports->contains($report)) {
            $this->assigned_reports[] = $report;
            $report->addManager($this);
        }

        return $this;
    }

    public function removeAssignedReport(Report $report): self
    {
        if ($this->assigned_reports->removeElement($report)) {
            $report->removeManager($this);
        }

        return $this;
    }

    public function getEvaluations(): Collection
    {
        return $this->evaluations;
    }

    public function setEvaluations(Collection $evaluations): self
    {
        $this->evaluations = $evaluations;

        return $this;
    }

    public function getAutocompleteValue(): string
    {
        return (string) $this->id;
    }

    public function getAutocompleteLabel(): string
    {
        return (string) $this->username;
    }

    public function getNotificationsReadAt(): ?\DateTimeImmutable
    {
        return $this->notifications_read_at;
    }

    public function setNotificationsReadAt(?\DateTimeImmutable $notifications_read_at): self
    {
        $this->notifications_read_at = $notifications_read_at;

        return $this;
    }
}

src/Domain/Shared/Entity/TimestampTrait.php
<?php

declare(strict_types=1);

namespace Domain\Shared\Entity;

/**
 * Trait TimestampTrait.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
trait TimestampTrait
{
    private ?\DateTimeImmutable $created_at = null;

    private ?\DateTimeImmutable $updated_at = null;

    public function setCreatedAtOnPrePersist(): void
    {
        if (null === $this->created_at) {
            $this->created_at = new \DateTimeImmutable();
        }
    }

    public function setUpdatedAtOnPostUpdate(): void
    {
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface|string $created_at): self
    {
        if (is_string($created_at)) {
            $date = \DateTimeImmutable::createFromFormat('Y-m-d H:i', $created_at);
            $this->created_at = false === $date ? null : $date;
        } elseif ($created_at instanceof \DateTimeInterface) {
            $this->created_at = \DateTimeImmutable::createFromInterface($created_at);
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface|string|null $updated_at): self
    {
        if (is_string($updated_at)) {
            $date = \DateTimeImmutable::createFromFormat('Y-m-d H:i', $updated_at);
            $this->updated_at = false === $date ? null : $date;
        } elseif ($updated_at instanceof \DateTimeInterface) {
            $this->updated_at = \DateTimeImmutable::createFromInterface($updated_at);
        } else {
            $this->updated_at = $updated_at;
        }

        return $this;
    }
}

src/Infrastructure/Administration/Symfony/Controller/UserController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Administration\Symfony\Controller;

use Application\Authentication\Command\DeleteUserCommand;
use Application\Authentication\Command\RegisterUserCommand;
use Application\Authentication\Command\UpdateUserCommand;
use Domain\Authentication\Entity\User;
use Infrastructure\Authentication\Doctrine\Repository\UserRepository;
use Infrastructure\Authentication\Symfony\Form\RegisterUserForm;
use Infrastructure\Authentication\Symfony\Form\UpdateUserForm;
use Infrastructure\Shared\Symfony\Controller\AbstractController;
use Infrastructure\Shared\Symfony\Controller\DeleteCsrfTrait;
use Infrastructure\Shared\Symfony\Controller\PaginationAssertionTrait;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * class UserController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[IsGranted('ROLE_ADMIN')]
#[Route('/admin/authentication/user', name: 'administration_user_')]
#[AsController]
final class UserController extends AbstractController
{
    use DeleteCsrfTrait;
    use PaginationAssertionTrait;

    #[Route('', name: 'index', methods: ['GET'])]
    public function index(Request $request, PaginatorInterface $paginator, UserRepository $repository): Response
    {
        $page = $request->query->getInt('page', 1);
        $this->assertIsGreaterThanZero($page);

        $data = $paginator->paginate($repository->findAll(), $page, 15);
        $this->assertNonEmptyData($page, $data);

        return $this->render(
            view: 'domain/administration/user/index.html.twig',
            parameters: [
                'data' => $data,
            ]
        );
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $command = new RegisterUserCommand();
        $form = $this->createForm(RegisterUserForm::class, $command)
            ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->dispatchSync($command);
                $this->addFlash('success', $this->translator->trans(
                    id: 'authentication.flashes.user_registered_successfully',
                    parameters: [
                        '%name%' => $command->username,
                    ],
                    domain: 'authentication'
                ));

                return $this->redirectSeeOther('administration_user_index');
            } catch (\Throwable $e) {
                $this->handleUnexpectedException($e);
                $response = new Response(status: Response::HTTP_UNPROCESSABLE_ENTITY);
            }
        }

        return $this->render(
            view: 'domain/administration/user/new.html.twig',
            parameters: [
                'form' => $form->createView(),
            ],
            response: $this->getResponseBasedOnFormValidationStatus($form, $response ?? null)
        );
    }

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render(
            view: 'domain/administration/user/show.html.twig',
            parameters: [
                'data' => $user,
            ]
        );
    }

    #[Route('/{id}', name: 'delete', methods: ['DELETE'])]
    public function delete(Request $request, User $user): Response
    {
        if ($this->isDeleteCsrfTokenValid((string) $user->getId(), $request)) {
            try {
                $this->dispatchSync(new DeleteUserCommand($user));
                $this->addFlash('success', $this->translator->trans(
                    id: 'authentication.flashes.user_deleted_successfully',
                    parameters: [
                        '%name%' => $user->getUsername(),
                    ],
                    domain: 'authentication'
                ));

                return $this->redirectSeeOther('administration_user_index');
            } catch (\Throwable $e) {
                $this->handleUnexpectedException($e);
            }
        } else {
            $this->addSomethingWentWrongFlash();
        }

        return $this->redirectSeeOther('administration_user_show', [
            'id' => $user->getId(),
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user): Response
    {
        $command = new UpdateUserCommand($user);
        $form = $this->createForm(UpdateUserForm::class, $command)
            ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->dispatchSync($command);
                $this->addFlash('success', $this->translator->trans(
                    id: 'authentication.flashes.user_updated_successfully',
                    parameters: [
                        '%name%' => $user->getId(),
                    ],
                    domain: 'authentication'
                ));

                return $this->redirectSeeOther('administration_user_show', [
                    'id' => $user->getId(),
                ]);
            } catch (\Throwable $e) {
                $this->handleUnexpectedException($e);
                $response = new Response(status: Response::HTTP_UNPROCESSABLE_ENTITY);
            }
        }

        return $this->render(
            view: 'domain/administration/user/edit.html.twig',
            parameters: [
                'form' => $form->createView(),
                'data' => $user,
            ],
            response: $this->getResponseBasedOnFormValidationStatus($form, $response ?? null)
        );
    }
}

templates/domain/administration/user/edit.html.twig
{% extends 'domain/report/layout/base.html.twig' %}
{% block title 'Modifier un utilisateur' %}

{% block header %}
    {% embed "shared/component/_header.html.twig" %}
        {% block header_title "Modifier un utilisateur" | title %}
        {% block header_action_list %}
            <li>
                <a href="{{ path('administration_user_show', {id: data.id}) }}" class="btn btn-white btn-dim btn-outline-light" aria-label="{{ 'global.back' | trans }}" title="{{ 'global.back' | trans }}">
                    {{ 'arrow-long-left' | icon }}
                    <span>Voir l'utilisateur</span>
                </a>
            </li>
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block content %}
    {% if app.user == data %}
        <div class="alert alert-danger alert-icon">
            {{ 'alert-circle' | icon }} Modifier les informations de votre propre compte entraîne une déconnexion
            et ceci peut également entraîner à une perte d'accès au système.
            Modifier vos informations depuis vos <a class="alert-link" href="{{ path('authentication_settings_index') }}">paramètres de profil</a>.
        </div>
    {% endif %}

    {% embed "shared/component/card/_simple.html.twig" %}
        {% block simple_card_body %}
            {% include 'shared/component/_form.html.twig' %}
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/domain/administration/user/index.html.twig
{% extends 'domain/report/layout/base.html.twig' %}
{% block title 'Utilisateurs' %}

{% block header %}
    {% embed 'shared/component/_header.html.twig' %}
        {% block header_title 'Utilisateurs' %}
        {% block header_action_list %}
            <li>
                <a href="{{ path('administration_user_new') }}" class="btn btn-white btn-dim btn-outline-light" aria-label="Ajouter un utilisateur" title="Ajouter un utilisateur">
                    {{ 'plus' | icon }}
                    <span>Ajouter un utilisateur</span>
                </a>
            </li>
           {#<li>
                <a href="{{ path('administration_user_new') }}" class="btn btn-white btn-dim btn-outline-light" aria-label="Ajouter un utilisateur" title="Ajouter un utilisateur">
                    {{ 'file' | icon }}
                    <span>Importer des utilisateurs</span>
                </a>
            </li>#}
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block content %}
    {% embed "shared/component/card/_list.html.twig" %}
        {% block list_card_table_head %}
            <th>#</th>
            <th>Nom complet</th>
            <th>Poste</th>
            <th>Email</th>
            <th>Rôle</th>
            <th>&nbsp;</th>
        {% endblock %}
        {% block list_card_table_body %}
            {% for row in data %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.username | u.truncate(60, '...') }}</td>
                    <td>{{ row.jobTitle }}</td>
                    <td>{{ row.email }}</td>
                    <td>{{ row.roles | last | badge }}</td>
                    <td class="tb-odr-action">
                        <div class="tb-odr-btns d-none d-md-inline">
                            <a href="{{ path('administration_user_show', {id: row.id}) }}" class="btn btn-sm btn-primary" title="{{ 'global.show' | trans([], 'messages') }}">
                                {{ 'eye-alt-fill' | icon }}
                                <span>{{ 'global.show' | trans([], 'messages') }}</span>
                            </a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/domain/administration/user/new.html.twig
{% extends 'domain/report/layout/base.html.twig' %}
{% block title 'Ajouter un utilisateur' %}

{% block header %}
    {% embed "shared/component/_header.html.twig" %}
        {% block header_title "Ajouter un utilisateur" | title %}
        {% block header_action_list %}
            <li>
                <a href="{{ path('administration_user_index') }}" class="btn btn-white btn-dim btn-outline-light" aria-label="{{ 'global.back' | trans }}" title="{{ 'global.back' | trans }}">
                    {{ 'arrow-long-left' | icon }}
                    <span>Tous les utilisateurs</span>
                </a>
            </li>
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block content %}
    {% embed "shared/component/card/_simple.html.twig" %}
        {% block simple_card_body %}
            {% include 'shared/component/_form.html.twig' %}
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/domain/administration/user/show.html.twig
{% extends 'domain/report/layout/base.html.twig' %}
{% block title "Utilisateur #{data.username}" %}

{% block header %}
    {% embed "shared/component/_header.html.twig" %}
        {% block header_title "Utilisateur #{data.username}" | title %}
        {% block header_action_list %}
            <li>
                <a href="{{ path('administration_user_index') }}" class="btn btn-white btn-dim btn-outline-light" aria-label="{{ 'global.back' | trans }}" title="{{ 'global.back' | trans }}">
                    {{ 'arrow-long-left' | icon }}
                    <span>Tous les utilisateurs</span>
                </a>
            </li>
            <li>
                <a href="{{ path('administration_user_edit', {id: data.id}) }}" class="btn btn-primary" aria-label="{{ 'global.edit' | trans([], 'messages') }}" title="{{ 'global.edit' | trans([], 'messages') }}">
                    {{ 'edit-alt-fill' | icon }}
                    <span>{{ 'global.edit' | trans([], 'messages') }}</span>
                </a>
            </li>
            {% if app.user != data %}
                <li>
                    <form class="d-inline-block" method="post" action="" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value='{{ csrf_token("delete_#{data.id}") }}'>
                        <button is="app-confirm-button" title="{{ 'global.delete' | trans([], 'messages') }}" aria-label="{{ 'global.delete' | trans([], 'messages') }}" class="btn btn-danger">
                            {{ 'trash-empty-fill' | icon }}
                            <span>{{ 'global.delete' | trans([], 'messages') }}</span>
                        </button>
                    </form>
                </li>
            {% endif %}
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block content %}
    {% embed "shared/component/card/_detail.html.twig" %}
        {% import 'shared/component/_macros.html.twig' as component %}
        {% block detail_card_body %}
            <div class="nk-block">
                <div class="nk-block-head">
                    <h5 class="title">Informations personnelles</h5>
                </div>
                <div class="profile-ud-list">
                    {{ component.user_data_item('Nom complet', data.username) }}
                    {{ component.user_data_item('Email', data.email) }}
                    {{ component.user_data_item('Poste', data.jobTitle) }}
                    {{ component.user_data_item('Genre', data.gender) }}
                    {{ component.user_data_item('Rôle', data.roles | last | badge) }}
                </div>
            </div>
            <div class="nk-divider divider md"></div>
            <div class="nk-block">
                <div class="nk-block-head">
                    <h5 class="title">Informations supplémentaires</h5>
                </div>
                <div class="profile-ud-list">
                    {{ component.user_data_item("2FA activé", data.is2FaEnabled() | boolean ) }}
                    {{ component.user_data_item("Dernière connexion", data.lastLoginAt ? data.lastLoginAt | date : '') }}
                    {{ component.user_data_item("Dernière Ip", data.lastLoginIp) }}
                    {{ component.user_data_item("Date de création", data.createdAt | date ) }}
                    {{ component.user_data_item("Dernière mise à jour", data.updatedAt ? data.updatedAt | date : '') }}
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}