src/Domain/Authentication/Entity/BackupAuthTrait.php
<?php

declare(strict_types=1);

namespace Domain\Authentication\Entity;

/**
 * Trait BackupAuthTrait.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
trait BackupAuthTrait
{
    private ?array $backup_codes = [];

    public function isBackupCode(string $code): bool
    {
        return in_array((int) $code, $this->getBackupCode(), true);
    }

    public function setBackupCode(?array $codes = []): self
    {
        if (null === $codes) {
            $this->backup_codes = [];
        } elseif (6 !== count($codes)) {
            throw new \InvalidArgumentException('Please set 6 backup codes with 6 digits long');
        } else {
            $this->backup_codes = $codes;
        }

        return $this;
    }

    public function getBackupCode(): array
    {
        return $this->backup_codes ?? [];
    }

    public function invalidateBackupCode(string $code): void
    {
        $backup_code = $this->getBackupCode();
        $this->backup_codes = array_filter($this->getBackupCode(), function (string $c) use ($code) {
            return $c !== $code;
        });
    }
}

src/Domain/Shared/Entity/TimestampTrait.php
<?php

declare(strict_types=1);

namespace Domain\Shared\Entity;

/**
 * Trait TimestampTrait.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
trait TimestampTrait
{
    private ?\DateTimeImmutable $created_at = null;

    private ?\DateTimeImmutable $updated_at = null;

    public function setCreatedAtOnPrePersist(): void
    {
        if (null === $this->created_at) {
            $this->created_at = new \DateTimeImmutable();
        }
    }

    public function setUpdatedAtOnPostUpdate(): void
    {
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface|string $created_at): self
    {
        if (is_string($created_at)) {
            $date = \DateTimeImmutable::createFromFormat('Y-m-d H:i', $created_at);
            $this->created_at = false === $date ? null : $date;
        } elseif ($created_at instanceof \DateTimeInterface) {
            $this->created_at = \DateTimeImmutable::createFromInterface($created_at);
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface|string|null $updated_at): self
    {
        if (is_string($updated_at)) {
            $date = \DateTimeImmutable::createFromFormat('Y-m-d H:i', $updated_at);
            $this->updated_at = false === $date ? null : $date;
        } elseif ($updated_at instanceof \DateTimeInterface) {
            $this->updated_at = \DateTimeImmutable::createFromInterface($updated_at);
        } else {
            $this->updated_at = $updated_at;
        }

        return $this;
    }
}

src/Infrastructure/Authentication/Symfony/Form/ConfirmResetPasswordForm.php
<?php

declare(strict_types=1);

namespace Infrastructure\Authentication\Symfony\Form;

use Application\Authentication\Command\ConfirmResetPasswordCommand;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ConfirmResetPasswordForm.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
final class ConfirmResetPasswordForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('password', RepeatedType::class, [
            'type' => PasswordType::class,
            'first_options' => [
                'label' => 'authentication.forms.labels.password',
            ],
            'second_options' => [
                'label' => 'authentication.forms.labels.password_confirm',
            ],
            'invalid_message' => 'authentication.validations.password_must_match',
        ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ConfirmResetPasswordCommand::class,
            'translation_domain' => 'authentication',
        ]);
    }
}

src/Infrastructure/Authentication/Symfony/Controller/Login2FAController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Authentication\Symfony\Controller;

use Application\Authentication\Command\Resend2FACodeCommand;
use Domain\Authentication\Entity\User;
use Infrastructure\Shared\Symfony\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\RateLimiter\Exception\RateLimitExceededException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * Class Login2FaController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
final class Login2FAController extends AbstractController
{
    #[Route('/login/2fa_resend_code', name: 'authentication_2fa_resend_code', methods: ['POST', 'GET'])]
    public function resend(Request $request, Security $security): Response
    {
        try {
            /** @var User|null $user */
            $user = $security->getToken()?->getUser();

            if (null !== $user) {
                $this->dispatchSync(new Resend2FACodeCommand((string) $request->getClientIp(), $user));
                $this->addFlash('success', $this->translator->trans(
                    id: 'authentication.flashes.resend_code_requested_successfully',
                    parameters: [],
                    domain: 'authentication'
                ));
            }
        } catch (RateLimitExceededException $e) {
            $this->addFlash('error', $this->translator->trans(
                id: 'authentication.flashes.too_many_resend_code_request',
                parameters: [],
                domain: 'authentication'
            ));
        } catch (\Throwable $e) {
            $this->handleUnexpectedException($e);
        }

        return $this->redirectSeeOther('authentication_2fa_login');
    }
}

src/Infrastructure/Authentication/Symfony/Controller/LoginFormController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Authentication\Symfony\Controller;

use Application\Authentication\Command\LoginCommand;
use Infrastructure\Authentication\Symfony\Form\LoginForm;
use Infrastructure\Shared\Symfony\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

/**
 * Class LoginFormController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[AsController]
#[Route('', name: 'authentication_')]
final class LoginFormController extends AbstractController
{
    #[Route('/login', name: 'login', methods: ['GET', 'POST'])]
    public function login(AuthenticationUtils $utils): Response
    {
        if ($this->getUser()) {
            $this->redirectToRoute('app_index');
        }

        $error = $utils->getLastAuthenticationError();
        $command = new LoginCommand();

        if (null !== $error) {
            $command->identifier = $utils->getLastUsername();
            $this->addFlash('error', $this->translator->trans(
                id: $error->getMessageKey(),
                parameters: $error->getMessageData()
            ));
        }

        $form = $this->createForm(LoginForm::class, $command);

        return $this->renderForm(
            view: 'domain/authentication/login.html.twig',
            parameters: [
                'form' => $form,
            ],
            response: $this->getResponseBasedOnFormValidationStatus($form)
        );
    }

    #[Route('/logout', name: 'logout', methods: ['POST'])]
    #[Route('/logout', name: 'logout', methods: ['GET'], condition: "'dev' === '%kernel.environment%'")]
    public function logout(): never
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

src/Infrastructure/Authentication/Symfony/Controller/LoginLinkController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Authentication\Symfony\Controller;

use Application\Authentication\Command\RequestLoginLinkCommand;
use Infrastructure\Authentication\Symfony\Form\RequestLoginLinkForm;
use Infrastructure\Shared\Symfony\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class LoginLinkController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[AsController]
#[Route('/login/link', name: 'authentication_login_link_')]
final class LoginLinkController extends AbstractController
{
    #[Route('/request', name: 'request', methods: ['GET', 'POST'])]
    public function request(Request $request): Response
    {
        if ($this->getUser()) {
            $this->redirectToRoute('app_index');
        }

        $command = new RequestLoginLinkCommand();
        $form = $this->createForm(RequestLoginLinkForm::class, $command)
            ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->dispatchSync($command);
                $this->addFlash('success', $this->translator->trans(
                    id: 'authentication.flashes.login_link_requested_successfully',
                    parameters: [],
                    domain: 'authentication'
                ));

                return $this->redirectSeeOther('authentication_login');
            } catch (\Throwable $e) {
                $this->handleUnexpectedException($e);
                $response = new Response(status: Response::HTTP_UNPROCESSABLE_ENTITY);
            }
        }

        return $this->render(
            view: 'domain/authentication/login_link.html.twig',
            parameters: [
                'form' => $form->createView(),
            ],
            response: $this->getResponseBasedOnFormValidationStatus($form, $response ?? null)
        );
    }

    #[Route('/check', name: 'check', methods: ['GET'])]
    public function check(): never
    {
        throw new \LogicException('This code should never be reached');
    }
}

src/Infrastructure/Authentication/Symfony/Controller/ResetPasswordController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Authentication\Symfony\Controller;

use Application\Authentication\Command\ConfirmResetPasswordCommand;
use Application\Authentication\Command\RequestResetPasswordCommand;
use Application\Authentication\Service\ResetPasswordService;
use Domain\Authentication\Entity\User;
use Domain\Authentication\Exception\ResetPasswordOngoingException;
use Domain\Authentication\Exception\ResetPasswordTokenExpiredException;
use Domain\Authentication\Exception\UserNotFoundException;
use Infrastructure\Authentication\Symfony\Form\ConfirmResetPasswordForm;
use Infrastructure\Authentication\Symfony\Form\RequestResetPasswordForm;
use Infrastructure\Shared\Symfony\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ResetPasswordController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[AsController]
#[Route('/password', name: 'authentication_reset_password_')]
final class ResetPasswordController extends AbstractController
{
    #[Route('/request/{id?}', name: 'request', methods: ['GET', 'POST'])]
    public function request(Request $request, ?User $user = null): Response
    {
        $command = new RequestResetPasswordCommand();

        if ($this->getUser()?->getUserIdentifier() === $user?->getUserIdentifier()) {
            $command = new RequestResetPasswordCommand(email: $user?->getEmail());
        }

        $form = $this->createForm(RequestResetPasswordForm::class, $command)
            ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->dispatchSync($command);
                $this->addFlash('success', $this->translator->trans(
                    id: 'authentication.flashes.reset_password_requested_successfully',
                    parameters: [],
                    domain: 'authentication'
                ));
            } catch (ResetPasswordOngoingException | UserNotFoundException $e) {
                $this->addFlash('error', $this->translator->trans(
                    id: $e->getMessageKey(),
                    parameters: $e->getMessageData(),
                    domain: 'authentication'
                ));
            } catch (\Throwable $e) {
                $this->handleUnexpectedException($e);
            }

            return $this->redirectSeeOther('authentication_login');
        }

        return $this->render(
            view: 'domain/authentication/reset_password_request.html.twig',
            parameters: [
                'form' => $form->createView(),
            ],
            response: $this->getResponseBasedOnFormValidationStatus($form)
        );
    }

    #[Route('/confirm/{token}', name: 'confirm', methods: ['GET', 'POST'])]
    public function confirm(string $token, ResetPasswordService $service, Request $request): Response
    {
        try {
            $token = $service->findToken($token);
        } catch (ResetPasswordTokenExpiredException) {
            $this->addFlash('error', $this->translator->trans(
                id: 'authentication.exceptions.reset_password_token_expired',
                parameters: [],
                domain: 'authentication'
            ));

            return $this->redirectSeeOther('authentication_login');
        }

        $command = new ConfirmResetPasswordCommand($token);
        $form = $this->createForm(ConfirmResetPasswordForm::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->dispatchSync($command);
                $this->addFlash('success', $this->translator->trans(
                    id: 'authentication.flashes.reset_password_confirmed_successfully',
                    parameters: [],
                    domain: 'authentication'
                ));

                return $this->redirectSeeOther('authentication_login');
            } catch (\Throwable $e) {
                $this->handleUnexpectedException($e);
            }

            $this->redirectSeeOther('authentication_login');
        }

        return $this->render(
            view: 'domain/authentication/reset_password_confirm.html.twig',
            parameters: [
                'form' => $form->createView(),
            ],
            response: $this->getResponseBasedOnFormValidationStatus($form)
        );
    }
}

src/Infrastructure/Authentication/Symfony/Controller/Setting/BackupCodeController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Authentication\Symfony\Controller\Setting;

use Application\Authentication\Command\ExportBackupCodeCommand;
use Application\Authentication\Command\RegenerateBackupCodeCommand;
use Domain\Authentication\Entity\User;
use Infrastructure\Shared\Symfony\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\HeaderUtils;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\Stamp\HandledStamp;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class BackupCodeSettingController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[IsGranted('IS_AUTHENTICATED_FULLY')]
#[Route('/profile/settings/security/backup_codes', name: 'authentication_setting_security_backup_codes_')]
final class BackupCodeController extends AbstractController
{
    #[Route('/regenerate', name: 'regenerate', methods: ['POST'])]
    public function regenerate(): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        try {
            $this->dispatchSync(new RegenerateBackupCodeCommand($user));
            $this->addFlash('success', 'Les codes ont été régénérés avec succès');
        } catch (\Throwable $e) {
            $this->handleUnexpectedException($e);
        }

        return $this->redirectSeeOther('authentication_setting_security');
    }

    #[Route('/export', name: 'export', methods: ['GET', 'POST'])]
    public function export(): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        try {
            $envelope = $this->dispatchSync(new ExportBackupCodeCommand($user));

            /** @var HandledStamp $stamp */
            $stamp = $envelope?->last(HandledStamp::class);

            $response = new Response(strval($stamp->getResult()));
            $response->headers->set('Content-Disposition', HeaderUtils::makeDisposition(
                disposition: HeaderUtils::DISPOSITION_ATTACHMENT,
                filename: 'unh_rapports_backup_code.txt'
            ));

            return $response;
        } catch (\Throwable $e) {
            $this->handleUnexpectedException($e);
        }

        return $this->redirectSeeOther('authentication_setting_security');
    }
}

templates/domain/authentication/setting/2fa.html.twig
{% extends 'domain/report/layout/base.html.twig' %}
{% block title 'Authentification à facteur double' %}

{% block content %}
    <div class="card">
        <div class="card-aside-wrap">
            <div class="card-inner card-inner-lg">
                <div class="nk-block-head nk-block-head-lg">
                    <div class="nk-block-between">
                        <div class="nk-block-head-content">
                            <h4 class="nk-block-title">Authentification à facteur double</h4>
                            <div class="nk-block-des">
                                <p>Ces paramètres vous aident à assurer la sécurité de votre compte.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="nk-block">
                    <div class="card border border-light">
                        <div class="card-inner-group">
                            {{ form_start(form) }}
                            <div class="card-inner">
                                <div class="between-center flex-wrap g-3">
                                    <div class="nk-block-text"> {{ form_row(form.email) }}</div>
                                </div>
                            </div>
                            <div class="card-inner">
                                <div class="flex-column">
                                    <div class="between-center flex-wrap flex-md-nowrap g-3">
                                        <div class="nk-block-text">
                                            <p>
                                                Si vous souhaitez vous utiliser <strong>Google Authenticator</strong>, <br>
                                                activez l'option et scannez ce qrcode depuis votre mobile.
                                            </p>
                                            {{ form_row(form.google) }}
                                            <img src="{{ qr_code_data_uri(qrcode_content) }}" alt="google authenticator qrcode">
                                        </div>
                                    </div>
                                    <button class="btn btn-primary mt-4">
                                        {{ 'save-fill' | icon }}
                                        <span>{{ 'global.submit' | trans([], 'messages') }}</span>
                                    </button>
                                </div>
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'domain/authentication/component/_setting_sidebar.html.twig' %}
        </div>
    </div>
{% endblock %}

templates/domain/authentication/setting/password.html.twig
{% extends 'domain/report/layout/base.html.twig' %}
{% block title 'Mettre à jour le mot de passe' %}

{% block content %}
    <div class="card">
        <div class="card-aside-wrap">
            <div class="card-inner card-inner-lg">
                <div class="nk-block-head nk-block-head-lg">
                    <div class="nk-block-between">
                        <div class="nk-block-head-content">
                            <h4 class="nk-block-title">Mettre à jour le mot de passe</h4>
                            <div class="nk-block-des">
                                <p>Ces paramètres vous aident à assurer la sécurité de votre compte.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="nk-block">
                    <div class="card border border-light">
                        <div class="card-inner-group">
                            <div class="card-body">
                                {{ form_start(form) }}
                                    {{ form_widget(form) }}
                                    <button class="btn btn-primary mt-4">
                                        {{ 'save-fill' | icon }}
                                        <span>{{ 'global.submit' | trans([], 'messages') }}</span>
                                    </button>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% include 'domain/authentication/component/_setting_sidebar.html.twig' %}
        </div>
    </div>
{% endblock %}

templates/domain/authentication/setting/profile.html.twig
{% extends 'domain/report/layout/base.html.twig' %}
{% block title 'authentication.titles.settings' | trans([], 'authentication') %}

{% block content %}
    <div class="card">
        <div class="card-aside-wrap">
            <div class="card-inner card-inner-lg">
                <div class="nk-block-head nk-block-head-lg">
                    <div class="nk-block-between">
                        <div class="nk-block-head-content">
                            <h4 class="nk-block-title">Informations personnelles</h4>
                            <div class="nk-block-des">
                                <p>Les informations concernant votre compte.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="nk-block">
                    <div class="card border border-light">
                        <div class="card-inner-group">
                            <div class="card-body">
                                {{ form_start(form) }}
                                {{ form_widget(form) }}
                                <button class="btn btn-primary mt-4">
                                    {{ 'save-fill' | icon }}
                                    <span>{{ 'global.submit' | trans([], 'messages') }}</span>
                                </button>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% include 'domain/authentication/component/_setting_sidebar.html.twig' %}
        </div>
    </div>
{% endblock %}

templates/domain/authentication/setting/security.html.twig
{% extends 'domain/report/layout/base.html.twig' %}
{% block title 'authentication.titles.settings' | trans([], 'authentication') %}

{% block content %}
    <div class="card">
        <div class="card-aside-wrap">
            <div class="card-inner card-inner-lg">
                <div class="nk-block-head nk-block-head-lg">
                    <div class="nk-block-between">
                        <div class="nk-block-head-content">
                            <h4 class="nk-block-title">Paramètres de securités</h4>
                            <div class="nk-block-des">
                                <p>Ces paramètres vous aident à assurer la sécurité de votre compte.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="nk-block">
                    <div class="card border border-light">
                        <div class="card-inner-group">
                            <div class="card-inner">
                                <div class="between-center flex-wrap g-3">
                                    <div class="nk-block-text">
                                        <h6>Mot de passe</h6>
                                        <p>Définissez un mot de passe unique pour protéger votre compte.
                                        </p>
                                    </div>
                                    <div class="nk-block-actions flex-shrink-sm-0">
                                        <ul class="align-center flex-wrap flex-sm-nowrap gx-3 gy-2">
                                           {%  if app.user.updatedAt %}
                                               <li class="order-md-last">
                                                   <em class="text-soft text-date fs-12px">Dernière mise à jour : {{ app.user.updatedAt | date }}</em>
                                               </li>
                                            {% endif %}
                                            <li>
                                                <a href="{{ path('authentication_setting_security_password') }}" class="btn btn-primary">Modifier le mot de passe</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="card-inner">
                                <div class="between-center flex-wrap flex-md-nowrap g-3">
                                    <div class="nk-block-text">
                                        <h6>
                                            Authentification à facteur double &nbsp;
                                            {% if app.user.is2FAEnabled() %}
                                                <span class="badge badge-success ms-0">Activée</span>
                                            {% else %}
                                                <span class="badge badge-danger ms-0">Désactivée</span>
                                            {% endif %}
                                        </h6>
                                        <p>
                                            Sécurisez votre compte avec la sécurité 2FA. Lorsqu'elle est activée, vous devez
                                            saisir non seulement votre mot de passe, mais aussi un code spécial en utilisant
                                            l'application. Vous pouvez recevoir ce code par dans l'application mobile.
                                        </p>
                                    </div>
                                    <div class="nk-block-actions flex-shrink-sm-0">
                                        <ul class="align-center flex-wrap flex-sm-nowrap gx-3 gy-2">
                                            <li class="order-md-last">
                                                <a href="{{ path('authentication_setting_security_2fa') }}" class="btn btn-primary">Modifier</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="card-inner">
                                <div class="between-center flex-wrap flex-md-nowrap g-3">
                                    <div class="flex-column">
                                        <div class="nk-block-text">
                                            <h6>Codes d'accès hors ligne</h6>
                                            <p>
                                                <code class="pb-4">
                                                    {% for index, code in app.user.backupCode %}
                                                        <strong class="font-weight-bold fs-22px">{{ code ~ '\t' }}</strong>
                                                        {% if index == 2 %}
                                                            <br>
                                                        {% endif %}
                                                    {% endfor %}
                                                </code>
                                            </p>
                                        </div>
                                        <div class="nk-block-actions mt-4">
                                            <ul class="align-center flex-wrap flex-sm-nowrap gx-3 gy-2">
                                                <li>
                                                    <form action="{{ path('authentication_setting_security_backup_codes_regenerate') }}" method="post" class="d-inline-block">
                                                        <button type="submit" class="btn btn-primary">Régénérer</button>
                                                    </form>
                                                </li>
                                                <li>
                                                    <a href="{{ path('authentication_setting_security_backup_codes_export') }}" class="btn btn-primary">
                                                        {{ 'download' | icon }}
                                                        <span>Télécharger (csv)</span>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% include 'domain/authentication/component/_setting_sidebar.html.twig' %}
        </div>
    </div>
{% endblock %}